# for module compiling
import os
Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
objs = []
list = os.listdir(cwd)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')

Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()

# 添加 drivers 目录
objs = [Glob('drivers/*.c')]

# 添加头文件路径
CPPPATH = [cwd + '/drivers']

group = DefineGroup('Drivers', objs, depend = [''], CPPPATH = CPPPATH)

Return('group')
